spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always
  config:
    import: db.yml
logging:
  level:
    root: debug